server:
  port: 80  # 默认是8080
  servlet:
    context-path: /boot # 默认是 /

spring:
  web:
    resources:
      static-locations: classpath:/webapp # 默认是 [/static | /public | /resources | /META-INF/resources]
      # 配置静态资源文件夹 一旦配置了 默认的静态资源文件夹就无法访问了
      # 外部访问静态资源的时候,不需要写静态资源文件夹